### ISSUE TITLE
Make success optional

### ISSUE THREAD

**Issue by walterchris** [facebookincubator/contest#152]
From time to time I do run commands that are allowed to fail because they do expect to fail (sometimes) - but it is nothing I can change. How do I work around these things? My current idea would be to implement an successOnFailure option which can be set within the test steps. Does that makes sense to you?

I know that I can also lower the barrier of "success rate" to work around this problem - but that's not what I want.

**Comment by insomniacslk** [comment]
Can you make an example of a scenario like this?

**Comment by walterchris** [comment]
In this particular case flashing via the BMC takes so long that the BMC at some point in time closes the connection down. That is meant as a failure - but that's not correct. I'd rather than hook on the serial with a timeout instead of assuming it failed.

**Comment by insomniacslk** [comment]
technically you can add an `|| true` at the end of the shell command, to ignore failures, but I think this use case needs a more robust solution long term.
A possibility is that we need to send SSH `keep-alive`s to the connection, and that might be just good enough to solve your problem.

Otherwise, Tmux and nohup are good enough to start the process but not to check the status, for which something custom might help. I'm happy to brainstorm some ideas on Slack, and report back here once we have an agreement :)
